package it.polimi.deib.provaFinale2014.alessandro.baldassari_francesco2.bertelli.communication.server.handler;

/**
 * Enums containing all the possible net operations supported by this System. 
 */
public enum GameProtocolMessage 
{
	
	// GAME MESSAGES
	
	NAME_REQUESTING_REQUEST ,
	
	NAME_REQUESTING_RESPONSE,
	
	NAME_REQUESTING_RESPONSE_RESPONSE ,
	
	MATCH_STARTING_NOTIFICATION ,
	
	MATCH_WILL_NOT_START_NOTIFICATION,
		
	SHEPERD_COLOR_REQUESTING_REQUEST,
	
	SHEPERD_COLOR_REQUESTING_RESPONSE,
	
	SHEPERD_INIT_ROAD_REQUESTING_REQUEST ,
	
	CHOOSE_SHEPERD_FOR_A_TURN_REQUESTING_REQUEST ,
	
	CHOOSE_SHEPERD_FOR_A_TURN_REQUESTING_RESPONSE ,
	
	SHEPERD_INIT_ROAD_REQUESTING_RESPONSE ,
	
	DO_MOVE_REQUESTING_REQUEST ,
	
	DO_MOVE_REQUESTING_RESPONSE ,
	
	CHOOSE_CARDS_ELEGIBLE_FOR_SELLING_REQUESTING_REQUEST,
	
	CHOOSE_CARDS_ELEGIBLE_FOR_SELLING_REQUESTING_RESPONSE ,
	
	CHOOSE_CARDS_TO_BUY_REQUESTING_REQUEST ,
	
	CHOOSE_CARDS_TO_BUY_REQUESTING_RESPONSE ,

	GENERIC_NOTIFICATION_NOTIFICATION ,

	GAME_CONCLUSION_NOTIFICATION ,
	
	// TECHNICAL MESSAGES
	
	UID_NOTIFICATION ,
	
	TRY_RESUME ,
	
	RESUME_SUCCEEED ,
	
	RESUME_FAILED ,
	
	GUI_CONNECTOR_NOTIFICATION
	
}
